name: ovbot

on:
  push:
    branches: [ python3 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'python3'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build python 3.10
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8 future
          ./CI/build.sh
